# Generated by Django 4.1.2 on 2023-01-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_location_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='skill',
        ),
    ]
